#
#Uncomment when db:reset
Rating.create(rating_name:'good')
Rating.create(rating_name:'bad')
State.create(status: 'Buying',color:'blue')
State.create(status: 'Selling',color:'green')
State.create(status: 'Completed',color:'gray')
ActiveStatus.create(name: 'active')
ActiveStatus.create(name: 'inactive')
ActiveStatus.create(name: 'finish')
UserStatus.create(name:'active')
UserStatus.create(name:'disabled')
Quality.create(name:'2nd hand')
Quality.create(name:'New')
#sample seeding for locations
Location.create(name:'Makati')
Location.create(name:'Pasay')
Location.create(name:'Quezon')
Category.create(name: 'Technology')
Category.create(name:'Art')
Category.create(name: 'Figure Hobby')
Category.create(name:'Clothing')
Category.create(name: 'Paper Printed / Books')
Category.create(name: 'Music')
